### ISSUE TITLE
не работает

### ISSUE THREAD

**Issue by typeok** [Snawoot/dumbproxy#1]
root@VPN-vps-server:/opt# ./dumbproxy -cert ./nginx-selfsigned.crt -key ./nginx-selfsigned.key -verbosity 10
MAIN    : 2020/06/14 11:04:17 main.go:76: INFO     Starting proxy server...
HTTPSRV : 2020/06/14 11:04:25 server.go:3059: http: TLS handshake error from 178.122.98.169:56928: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:25 server.go:3059: http: TLS handshake error from 178.122.98.169:12025: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:25 server.go:3059: http: TLS handshake error from 178.122.98.169:56930: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:25 server.go:3059: http: TLS handshake error from 178.122.98.169:12027: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:25 server.go:3059: http: TLS handshake error from 178.122.98.169:56932: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:26 server.go:3059: http: TLS handshake error from 178.122.98.169:12029: remote error: tls: bad certificate
HTTPSRV : 2020/06/14 11:04:26 server.go:3059: http: TLS handshake error from 178.122.98.169:56934: remote error: tls: bad certificate

tls: bad certificate - это выходит тогда когда я пытаюсь через ФФ зайти куда нибудь, а в ФФ я вижу следующие - Did Not Connect: Potential Security Issue

Генерил серт и ключи вот так - openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout "$PWD"/nginx-selfsigned.key -out nginx-selfsigned.crt -subj "/C=$randC/ST=$randSt/L=$randSt/O=$randO/OU=$randOU/CN=$randCN.com"

Не могли бы помочь разобраться в чем проблема ? спасибо.

**Comment by Snawoot** [comment]
Добрый день!

Это файрфоксу не нравится самоподписанный сертификат и он отправляет TLS alert серверу. Сервер видит эту ошибку и логирует remote error.

Если у вас самоподписанный сертификат, то Вам нужно установить CA-сертификат или в сам браузер, или в систему (тогда нужно будет ещё включить `security.enterprise_roots.enabled` в about:config). Кроме того, сертификат конечной сущности (тот, который использует сервер) должен быть выписан на доменное имя или адрес, которое используется при подключении с клиента, иначе при несовпадении всё равно клиент (браузер) отвергнет его. Через openssl сгенерировать нормальный сертификат достаточно трудно - нужно ещё сделать конфиг, который добавляет нужное поле SAN в сертификат, потому что современные браузеры игнорируют значение поля CN сертификата.

Поэтому, если вы хотите сгенерировать такой сертификат, проще воспользоваться утилитой [quickcerts](https://github.com/Snawoot/quickcerts).

Но ещё лучше использовать бесплатные "белые" сертификаты Let'sEncrypt, потому что тогда никакая дополнительная настройка CA на клиенте не потребуется. Если у вас уже есть на сервере домен и nginx, получить такой сертификат будет даже проще, чем генерировать что-то самому и уж тем более ставить на клиенты.

**Comment by gxacker** [comment]
У меня после простоя (с утра например) выскакивает похожая ошибка в chromium.
При этом на стороне клиента: ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -202
На сервере: HTTPSRV : 2020/06/15 05:11:45 server.go:3059: http: TLS handshake error from 80.83.239.10:1806: remote error: tls: unknown certificate
Запускаю так, используя сертификаты Let's Encrypt: dumbproxy -bind-address :12345 -cert cert.pem -key key.pem -auth 'static://?username=user&password=1234'
Пробовал и с SwitchyOmega и из консоли запускать с прокси.
При этом в firefox такого не наблюдается, вернее один раз может выскачить ошибка, но при обновлении страницы все норм.

**Comment by Snawoot** [comment]
> У меня после простоя (с утра например) выскакивает похожая ошибка в chromium.

О, вот это интересно.

> При этом на стороне клиента: ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -202

Это такая ошибка в chromium-е выскакивает?

**Comment by gxacker** [comment]
> Это такая ошибка в chromium-е выскакивает?
Да, в консоли. В самом хромиуме страничка с ERR_PROXY_CERTIFICATE_INVALID.

**Comment by Snawoot** [comment]
Да любой прокси-свитчер, их много. Искать proxy switcher или proxy manager.

Но я думаю, дело не в нём - дополнения не могут влиять на проверку сертов, это явно какая-то проблема или с сертом, или с браузером.

Я сейчас потестил https-прокси в chromium (81.0.4044.138) - у меня никаких ошибок нет, но браузер почему-то сам по себе тормозит. В Firefox у меня получается в speedtest-е скорость 80-90 Мбит/c, в хромиуме - постоянно 15-20 Мбит/c через тот же самый прокси с тем же сервером speedtest.

Принимая это всё во внимание, рекомендую тогда на стороне клиента использовать [steady-tun](https://github.com/Snawoot/steady-tun), чтобы он сообщался с удалённым прокси-сервером через TLS, а браузер настроить на локальный порт как обычный HTTP-прокси без шифрования.

Например, вот так:

```
steady-tun -timeout 300s -dsthost example.com -dstport 8080
```

Для автозапуска удобно создать вот такой systemd-юнит:

```
[Unit]
Description=Secure TLS tunnel with pool of prepared upstream connections

[Service]
ExecStart=/home/user/bin/steady-tun -ttl 300s -dsthost example.com -dstport 8080
Restart=always
KillMode=process
TimeoutStartSec=5
TimeoutStopSec=5

[Install]
WantedBy=default.target
```

поместить его в `~/.config/systemd/user/steady-tun-http.service` и запустить:

```sh
systemctl --user daemon-reload
systemctl --user enable steady-tun-http
systemctl --user start steady-tun-http
```

логи смотреть вот так:

```sh
journalctl --user -u steady-tun-http
```

**Comment by vctr13** [comment]
Добрый день. Хотел попробовать сначала в локальной сети: 
1. На оном ПК (с IP 192.168.0.5) через батник запустил dumbproxy -bind-address :1234 -auth 'static://?username=admin&password=123456'
2. На втором ПК вставил data:,function FindProxyForURL(u, h){return "HTTPS example.com:8080";} в  Automatic proxy configuration URL - браузер не воспринимает видимо эту строку и на сайты не заходит
 Попробовал в  extension FoxyProxy  пишу data:,function FindProxyForURL(u, h){return "HTTPS example.com:8080";}
на что FF говорит что не видит данный файл. Хорошо, создал PAC.dat со следующим содержимым:
function FindProxyForURL(u, h){return "HTTPS 192.168.0.5:1234";}

Теперь при попытке загрузить какую-нибудь страницу браузер выдает "SECURE CONNECTION FAILED An error occured during a connection to 192.168.0.5:1234. SSL received a record that exceeded the maximum permissible length. Error code: SSL_ERROR_RX_RECOED_TOO_LONG "

Можно/нужно прописать аутентификацию, чтобы браузер заходил на прокси? Или что можно еще сделать?

Пробовал ставить вместо HTTPS PROXY (правильно ли это или должно быть именно HTTPS?) 
function FindProxyForURL(u, h){return "PROXY 192.168.0.5:1234";}
, тогда на ПК-прокси в командной строке отображается запрос со второго ПК на сайт, 
а расширение FoxyProxy выдает сообщение "the username/password combination used previously did not work " и ПК-прокси разрывает соединение.

Как можно Настроить данную схему?

Вообще, что мне нужно: Чтобы на одном ПК с IP1 работал Прокси-сервер, а с другого ПК можно было бродить в интернете через IP1 и чтобы сайты не видели, что работа идет через прокси.

Я так понимаю тут еще один момент: Нужно пробросить маршрут на роутере, чтобы запросы на определенный порт (1234 в нашем случае) попадали на нужный пк с прокси, так?

Получается, если это домашний комп, то прокси не настроить, а если Офисный со статикой, то можно прописать проброс (если есть доступ к роутеру), так?

**Comment by Snawoot** [comment]
Здравствуйте!

> через батник запустил dumbproxy -bind-address :1234 -auth 'static://?username=admin&password=123456'

> На втором ПК вставил data:,function FindProxyForURL(u, h){return "HTTPS example.com:8080";} в Automatic proxy configuration URL - браузер не воспринимает видимо эту строку и на сайты не заходит

Вы запустили прокси в режиме без TLS (обычный HTTP) и подключаетесь к нему как к HTTPS.

> Я так понимаю тут еще один момент: Нужно пробросить маршрут на роутере, чтобы запросы на определенный порт (1234 в нашем случае) попадали на нужный пк с прокси, так?

Обычно нет. Тут много вопросов и не совсем понятно, что в итоге должно получиться. Но, я думаю, что решим в любом случае. Напишите мне лучше в Telegram или куда-то ещё. Контакты в моём [профиле](https://github.com/Snawoot).
