### ISSUE TITLE
LetEncrypt certs

### ISSUE THREAD

**Issue by juev** [Snawoot/dumbproxy#12]
Hello!

I was try to use dumbproxy on my own server.

I used article from [habr](https://habr.com/ru/post/687512/) and runes dumbproxy from binary.

When dumbproxy started and I send request for checking:
```
curl -x 'https://USERNAME:PASSWORD@DOMAIN' http://ifconfig.co
```

I got error:

```
Sep 12 09:45:55 ip-xxx-xx-xx-xxx dumbproxy[13455]: HTTPSRV : 2022/09/12 09:45:55 server.go:3228: http: TLS handshake error from 79.139.170.228:2054: acme/autocert: unable to satisfy "https://acme-v02.api.letsencrypt.org/acme/authz-v3/152466746267" for domain "123.example.com": no viable challenge type found
```

ps: USERNAME/PASSWORD/domain and IP was hidden.

Whats wrong??

And one more question. Do you tried to use dumbproxy with Cloudflare proxy?

**Comment by Snawoot** [comment]
Hi!

> Whats wrong??

Apparently domain ownership can't be verified by letsencrypt and it can't issue certificate. Is it a public domain attached to server address?

> Do you tried to use dumbproxy with Cloudflare proxy?

I didn't, but it will not work for sure.

**Comment by juev** [comment]
Thank you!
