### ISSUE TITLE
exec /dumbproxy: operation not permitted

### ISSUE THREAD

**Issue by AngieLarkin** [Snawoot/dumbproxy#14]
Запустил контейнер командой:
`docker run -d     --security-opt no-new-privileges     -p 8080:8080     --restart unless-stopped     --name dumbproxy     yarmak/dumbproxy`

Контейнер висит в рестарте.
В логе ошибка:
`exec /dumbproxy: operation not permitted`

ОС: Ubuntu 22.04
Docker 20.10.17

**Comment by Snawoot** [comment]
Здравствуйте!

У меня не воспроизводится данная проблема - всё в порядке с докером.
