### ISSUE TITLE
Есть ли подробная инструкция для настройки клиент на mac OS?

### ISSUE THREAD

**Issue by D1maD1m0nd** [Snawoot/dumbproxy#19]
Привет , столкнуолся с проблемой настройки на mac OS
Пробую через .pac файл указывать настройки прокси сервера, вот его содержимое
function FindProxyForURL(u, h) {
    return "HTTPS exaple.com:443";
}
тот же конфиг работает в ОС windows и linux
что может быть не так?

**Comment by Snawoot** [comment]
Привет! У меня нету под рукой мака - не написал инструкцию. Но такая бы точно пригодилась.

Какой браузер? Safari?

**Comment by D1maD1m0nd** [comment]
Привет, у меня тоже нет мака я настраивал девушке и у меня получилось, но не так как я хотел(
Я пытался через настройки мака, а не конркетный барузер
Вот шаги, которые я предпринял, что бы все завелось
создал .pac файл с содержимым 
```
function FindProxyForURL(u, h) {
    return "HTTPS example.com:443";
}
```
выложил его к себе на сервер и расшарил
Открыл "Системные настройки" на  Mac и выбрал **"Сеть"**.
Перешел на вкладку **"Прокси**" и выберал **"Автоматическая настройка прокси**".
Ввел адрес URL-адрес PAC-файла в поле **"URL PAC-файла**" http://example.com/proxy.pac.
и применил
Основая проблема в том, что я не понял то как указать путь до .pac файла, который находится на маке
поидее должно быть что то воде file://file_system_path/, но видимо я что то упустил

**Comment by mortum5** [comment]
Есть способ через энкодирование в base64, в целом рабочее, но проще было в другом браузере. Я просто добавил в Firefox там есть настройка на уровне браузера, в отличие от Chrome
