### ISSUE TITLE
Как настроить через докер?

### ISSUE THREAD

**Issue by doroved** [Snawoot/dumbproxy#20]
Привет, подскажи, после запуска контейнера в докере, что надо сделать, чтобы настроить HTTPS прокси?
Не совсем понятно.
Хотел запустить эту команду внутри контейнера
```BASH
dumbproxy -bind-address :443 -auth 'static://?username=admin&password=123456' -autocert
```
Но не пускает в контейнер
```BASH
root@HTTPS-proxy:~# docker exec -it dumbproxy bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "bash": executable file not found in $PATH: unknown
```

Может команда для поднятия контейнера для HTTPS прокси иначе должна быть, в общем нужна подробнее инструкция. Спасибо)

**Comment by Snawoot** [comment]
привет!

> Но не пускает в контейнер

Не пускает потому, что в том контейнере кроме исполняемого файла dumbproxy ничего нет, ни баша, вообще ничего. Если вам нужен шелл внутри контейнера, то можете воспользоваться другим докер-образом с шеллом и всем таким: `yarmak/dumbproxy:latest-alpine`

Но в целом это не обязательно, вы можете просто запустить обычный образ вот так:

```
docker run -d \
    --security-opt no-new-privileges \
    -p 443:443 \
    --restart unless-stopped \
    --name dumbproxy \
    yarmak/dumbproxy -bind-address :443 -auth 'static://?username=admin&password=123456' -autocert
```

Инструкция по запускую в докере есть в ридми, в общих чертах даёт представление: https://github.com/Snawoot/dumbproxy#docker
