### ISSUE TITLE
nginx + dumbproxy

### ISSUE THREAD

**Issue by muravjov** [Snawoot/dumbproxy#23]
Is it possible to run nginx on 443 for TLS termination and pass a request to dumbproxy for real work?
TLS support is a great thing, but the port 443 is occupied by nginx, as usual (to serve multiple http services).

If yes, can you provide a somewhat working nginx config for nginx + dumbproxy pair. (is standard proxy_pass ok?)

P.S. The question suits better for StackOverflow, seems like. But I feel better to land it here.

**Comment by Snawoot** [comment]
> Is it possible to run nginx on 443 for TLS termination and pass a request to dumbproxy for real work?
TLS support is a great thing, but the port 443 is occupied by nginx, as usual (to serve multiple http services).

It's definitely possible with haproxy. But I'm not sure about nginx: it's not clear if it has same special treatment for CONNECT method as haproxy does.

> If yes, can you provide a somewhat working nginx config for nginx + dumbproxy pair. (is standard proxy_pass ok?)

I haven't tried it. But proxy_pass should do, I guess. If you'll manage to configure it this way, it may be a nice addition for recipes in [project wiki](https://github.com/Snawoot/dumbproxy/wiki).
