### ISSUE TITLE
не удаётся подключиться с сертификатами

### ISSUE THREAD

**Issue by skypiece** [Snawoot/dumbproxy#3]
Без аутентификации всё в норме.
Серверные сертификаты (от Let's Encrypt) сходу работают (например, в связке с -auth "static://?username=user&password=1234").
На самоподписанный клиентский программы ругаться перестают после добавления ca.pem в список доверенных корневых (x509: certificate signed by unknown authority).

Но реальная проблема пришла откуда не ждали. Провайдер перехватывает сертификаты и подменяет на свои (steady-tun: x509: certificate has expired or is not yet valid: current time 2021-02-25T14:55:50+03:00 is after 2018-02-07T07:50:50Z;
ptw: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain).

Аналогичная проблема с доступом к своему веб-серверу Apache, расположенному на одном хосте с dumbproxy, решилась просто - убрал лишнее из параметра SSLCipherSuite. Например, TLS_CHACHA20_POLY1305_SHA256 посредник не перехватывает, а TLS_AES_128_GCM_SHA256 ломает.

В связи с этим, прошу добавить параметр для ограничения списка возможных механизмов обмена ключами.

**Comment by Snawoot** [comment]
> На самоподписанный клиентский программы ругаться перестают после добавления ca.pem в список доверенных корневых (x509: certificate signed by unknown authority).

Вообще по идее достаточно указать `-cafile ca.pem` чтобы считать их доверенными.

> Провайдер перехватывает сертификаты и подменяет на свои

Это Казахстан?

> В связи с этим, прошу добавить параметр для ограничения списка возможных механизмов обмена ключами.

Попробую заняться этим в ближайшее время.

**Comment by skypiece** [comment]
В моём случае точно нет (W 10 Pro 1909 и WSL2 Ubuntu 20.4). Проверял на одной машине, но через доменное имя сервера. Пока не добавил ca в доверенные, всплывала ошибка.
Это сеть в крупной российской компании, где серьёзно заморачиваются с безопасностью.
Спасибо.

**Comment by Snawoot** [comment]
Если клиент использует самоподписанный клиентский сертификат для аутентификации, то в доверенный надо добавлять только на сервере ca.pem. На сервере при этом самоподписанный использовать не нужно: letsencrypt так же пойдёт. Другими словами, серты клиента и сервера не обязательно должны быть заверены одним УЦ.

**Comment by skypiece** [comment]
Да, всё так. Полагаю, изначально путаница в голове возникла как раз из-за слабого понимания работы сертификатов. И использование одной машины ясности не добавляло.
А вот следование по пути усложнения **none** -> **static** и только потом **cert** позволило вспомнить, как эта кухня устроена.
Следует добавить пример вызова, согласующийся с именами файлов ваших quickcerts и steady-tun на главную страницу:
dumbproxy \
	-bind-address ":8080" \
	-auth "cert://"
	-cafile "ca.pem" \
	-cert "site.com.pem" \
	-key "site.com.key"
Сейчас там только простой вариант с none.

**Comment by Snawoot** [comment]
Проблема решена в версии 1.4.0. Добавлены следующие опции:

```
  -ciphers string
    	colon-separated list of enabled ciphers
  -disable-http2
    	disable HTTP2
```
