### ISSUE TITLE
`acme/autocert: missing server name` HTTPSRV error

### ISSUE THREAD

**Issue by antokarev** [Snawoot/dumbproxy#30]
Hey there!

Trying to set up HTTPS proxy under VSCode [proxy settings](https://docs.mend.io/en-US/bundle/wsk/page/how_to_set_up_proxy_settings_for_advise_for_visual_studio_code.html) but constantly receive errors during TLS handshake.

`dumbproxy` log:
```shell
Apr 21 10:48:25 proxy-srv-1 dumbproxy[4349]: PROXY   : 2023/04/21 10:48:25 handler.go:131: INFO     Request: 77.33.111.33:62189 "" HTTP/1.1 CONNECT //github.com:443
Apr 21 10:48:25 proxy-srv-1 dumbproxy[4349]: PROXY   : 2023/04/21 10:48:25 handler.go:131: INFO     Request: 77.33.111.33:62189 "johndoe" HTTP/1.1 CONNECT //github.com:443
Apr 21 10:48:25 proxy-srv-1 dumbproxy[4349]: HTTPSRV : 2023/04/21 10:48:25 server.go:3228: http: TLS handshake error from 77.33.111.33:62192: acme/autocert: missing server name
```

VSCode client log:
```shell
[ERROR] [default] [2023-04-21T18:10:27.709Z] GitHub Copilot could not connect to server. Extension activation failed: "tunneling socket could not be established, cause=connect ECONNREFUSED 33.77.11.66:80"
```

`/etc/default/dumbproxy`:
```
dumbproxy -auth "basicfile://?path=/etc/dumbproxy.htpasswd" -autocert -bind-address :443
```

VSCode `settings.json`:
```json
{
  "http.proxy": "https://johndoe:12345qwert@proxy.example.org"
  "http.proxyStrictSSL": false,
  "http.proxySupport": "on"
}
```

But there are no issues using `cURL`❗️:
```shell
❯ curl -x 'https://johndoe:12345qwert@proxy.example.org' https://copilot-proxy.githubusercontent.com/_ping
{"now":1682100802,"status":"ok"}
```
```shell
Apr 21 18:13:22 proxy-hel1-1 dumbproxy[7176]: PROXY   : 2023/04/21 18:13:22 handler.go:131: INFO     Request: 77.37.131.83:57276 "atkrv" HTTP/1.1 CONNECT //copilot-proxy.githubusercontent.com:443
```

I'm actually confused and can't get why I get `cause=connect ECONNREFUSED 33.77.11.66:80` on port `80`❗️and why there's no server name 😕 

Would be grateful for any assistance 🙏

**Comment by Snawoot** [comment]
@antokarev 

Hi!

There is a catch: if you use HTTPS and `-autocert` option you have to specify server address using some **domain name**, not direct IP address. Otherwise certificate won't be issued.

It works like this.

Proxy client uses HTTPS and if server address is specified by domain name it will cause SNI extension with domain name to be added to TLS handshake. Proxy server receives such request and checks domain name in SNI extension of TLS handshake. It will try to issue certificate by ACME for that domain, but won't be able to issue certificate just for direct IP address (even though such certificates are technically possible.

So all you have to do is bind some domain to your server and refer to this proxy by its domain name.

Here is a complete deployment guide which also covers quick and free domain assignment:

* [English](https://github.com/Snawoot/dumbproxy/wiki/Quick-deployment)
* [Russian](https://habr.com/ru/articles/687512/)

**Comment by antokarev** [comment]
Thank you @Snawoot for such a detailed answer.

The only thing to clarify is
>you have to specify server address using some domain name

Where exactly should I specify my domain in `dumbproxy` config?

**Comment by Snawoot** [comment]
@antokarev 

> Where exactly should I specify my domain in `dumbproxy` config?

You don't need to, that's the thing. As I said before, domain name is visible in the SNI extension of TLS handshake and proxy will know domain name right in the moment when connection was made. It will do the rest automatically.

**Comment by antokarev** [comment]
In that case I guess I have some issue with Cloudflare DNS service and `dumbproxy`.

**Comment by Snawoot** [comment]
@antokarev Should work fine as long as you don't proxy traffic through cloudflare and use it just for DNS.

**Comment by antokarev** [comment]
Yup, traffic proxying is disabled.

**Comment by antokarev** [comment]
Same.

Online lookup tools indicates, that my domain has been propagated worldwide (A record was done less the 48h ago).

`curl -x 'https://johndoe:12345qwert@proxy.example.org' https://copilot-proxy.githubusercontent.com/_ping` works well too.

But not the VSCode 🙁

![CleanShot 2023-04-22 at 00 29 15@2x](https://user-images.githubusercontent.com/28726429/233737698-4e54c1e6-e8c2-48df-a4bc-a0625d84abd1.png)

**Comment by Snawoot** [comment]
@antokarev 

Wrong port number, apparently. Use 443 in settings of vscode.

**Comment by Snawoot** [comment]
Ah, forgot to mention: it's quite possible vscode itself can't work with HTTPS proxies. Most programs support only plain HTTP proxies (without any TLS wrapping connection). In that case you'll have to try either configure proxy system wide via PAC file returning HTTPS proxy or use wrapper on client side to connect to a HTTPS proxy like this one: [steady-tun](https://github.com/Snawoot/steady-tun). By the way, this wrapper also saves time for TLS connection, doing connection pooling in advance.

**Comment by antokarev** [comment]
<img width="775" alt="CleanShot 2023-04-22 at 00 36 10@2x" src="https://user-images.githubusercontent.com/28726429/233738355-6cfcad59-d62a-471b-b3a0-20047e0cf84b.png">

![CleanShot 2023-04-22 at 00 36 21@2x](https://user-images.githubusercontent.com/28726429/233738451-944f78b3-98b6-4f7d-948c-cf8f6ec0f025.png)

**Comment by Snawoot** [comment]
Not sure, why does it try port 80 on your screenshot [here](https://github.com/Snawoot/dumbproxy/issues/30#issuecomment-1518352517)?

Also in that context `https_proxy` is a regular proxy used to do HTTPS connects, not a HTTP proxy via TLS (as in our case). Most likely you'll need a wrapper on the client side to connect to a remote proxy via TLS and expose plaintext port on local address.

**Comment by antokarev** [comment]
I wonder why `80` too.

>or use wrapper on client side to connect to a HTTPS proxy like this one: [steady-tun](https://github.com/Snawoot/steady-tun)

Anyway, how can I connect to my proxy via `steady-tun` using basic auth?

I've look through https://github.com/Snawoot/steady-tun/tree/v1.2.0#usage-example, but I can't see any auth methods and don't have any `cert`/`key`/`cafile` to present.

**Comment by antokarev** [comment]
Well, I think I solved it:
![CleanShot 2023-04-22 at 01 38 02@2x](https://user-images.githubusercontent.com/28726429/233744651-cdc1ca42-ceb4-4cf0-be30-bc13eb85c9d0.png)

The last thing to do - add `steady-tun` to MacBook's autostart 🙂 

Thank you for your time and tools, @Snawoot 🙏 

PS. I'll consider donation if I ever will deal with c-currencies.
