### ISSUE TITLE
Using custom certficate files

### ISSUE THREAD

**Issue by VahidN** [Snawoot/dumbproxy#32]
I have `cert.crt` and `private.key` SSL/TLS certificate files for my domain from cloudflare. Is it possible to use them here?

**Comment by Snawoot** [comment]
P.S. Note that cert should include complete certificate chain with all intermediate certificaes, not just single leaf certificate.

**Comment by GordiNoki** [comment]
> P.S. Note that cert should include complete certificate chain with all intermediate certificates, not just single leaf certificate.

Please, specify this in wiki or manpage, since it my case it was not obvious to use fullchain.pem file from certbot rather then cert.pem
