### ISSUE TITLE
Сертификаты

### ISSUE THREAD

**Issue by visitoid** [Snawoot/dumbproxy#37]
Добрый день!

Прописал сертификаты, которые были получены по средствам скрипта acme.sh:

Запускаю прокси, следующей командой

./dumbproxy -cert /root/.acme.sh/abababa.ru_ecc/fullchain.cer -key /root/.acme.sh/abababa_ecc/abababa.ru.key -cafile /root/.acme.sh/abababa.ru_ecc/ca.cer

Всё отлично стартует, но при попытке подключиться к прокси выдаёт ошибку:

HTTPSRV : 2023/09/01 20:47:53 server.go:3215: http: TLS handshake error from a.b.c.d:54806: tls: first record does not look like a TLS handshake

**Comment by Snawoot** [comment]
@visitoid Здравствуйте!

Судя по всему, вы пытаетесь подключиться к прокси как к обычному HTTP-прокси, а не как к HTTPS-прокси. Обратите внимание на [секцию про настройку клиентов в документации](https://github.com/Snawoot/dumbproxy#using-http-over-tls-proxy). Если вы пользуетесь прокси для браузера, то я бы порекомендовал расширение Proxy SwitchyOmega.

**Comment by Snawoot** [comment]
Особо отмечу, что есть некоторая путаница в настройках прокси: в некоторых случаях можно указать отдельно прокси для разных протоколов HTTP, HTTPS, FTP, ..., но это будет обычный прокси **для** HTTPS, а не **через** HTTPS.

**Comment by visitoid** [comment]
А какие имеются аналоги на Android, кроме Adguard?

**Comment by Snawoot** [comment]
Clash, Drony по-моему. Но я не проверял их.

**Comment by tiaga** [comment]
> А какие имеются аналоги на Android, кроме Adguard?

SagerNet или NekoBox. Подробнее тут: https://github.com/net4people/bbs/issues/195
