### ISSUE TITLE
What is a "plain proxy"?

### ISSUE THREAD

**Issue by ygguser** [Snawoot/dumbproxy#43]
Do I understand correctly that when I run such a command line, I will get a regular http proxy without traffic encryption?
```
dumbproxy -bind-address :1234 -auth 'static://?username=admin&password=123456'
```

**Comment by Snawoot** [comment]
Yes. Look for `-cert`, `-key` or `-autocert` options to enable TLS encryption. Also there is a [complete walkthrough](https://github.com/Snawoot/dumbproxy/wiki/Quick-deployment) in wiki to setup proxy with encryption and automatic certs.
