### ISSUE TITLE
Не работает с программами Proxyfire, ProxyCap

### ISSUE THREAD

**Issue by heggi** [Snawoot/dumbproxy#45]
![image](https://github.com/Snawoot/dumbproxy/assets/1910657/ddba874b-d623-43ad-8dc7-69fabe17d633)

Логи Proxyfire:
```
[57:37] Testing Started.
  Proxy Server
  Address:  xxxxxxxxxxx:1443
  Protocol:  HTTPS
  Authentication: Basic
  Username:  proxy

[57:37] Starting: Test 1: Connection to the Proxy Server
[57:37] IP Address: xx.xx.xx.xx
[57:37] Connection established
[57:37] Test passed.
[57:37] Starting: Test 2: Connection through the Proxy Server
[57:37] Error : connection to the proxy server was closed unexpectedly.
  Please make sure that the proxy server protocol and address are correct.
[57:37] Test failed.
[57:37] Testing Finished.
```

Логи dumbproxy:
```
HTTPSRV : 2023/12/03 11:57:39 server.go:3212: http: TLS handshake error from xx.xx.xx.xx:1434: tls: first record does not look like a TLS handshake
```

Запускаю так:
`/usr/local/bin/dumbproxy -auth basicfile://?path=/etc/dumbproxy.htpasswd -bind-address :1443 -cert /etc/letsencrypt/live/xxxx/fullchain.pem -key /etc/letsencrypt/live/xxxx/privkey.pem`

В браузере прокси работает.
Proxifire с платными https прокси работает. 

Куда копать?

**Comment by heggi** [comment]
Спасибо!
Да, без tls логи стали нормальные (правда тест все-равно не проходит, тупо зависает)
Очевидно, что авторы программы вводят в заблуждение про поддержку https прокси :(

**Comment by Snawoot** [comment]
> Очевидно, что авторы программы вводят в заблуждение про поддержку https прокси :(

Это просто старая терминология, когда в браузерах отдельно выставлялись прокси для HTTP, HTTPS и FTP.

Зависает может потому что DPI плаинтекстовые прокси режет или типа того. Запустите тогда либо ещё один dumbproxy на клиенте по тому рецепту выше, либо [steady-tun](https://github.com/Snawoot/steady-tun). steady-tun ещё и задержку на TLS-подключение скрадывает, так как держит пул готовых подключений к TLS-апстриму. Тогда у вас получится самый обычный простой HTTP-прокси локально, с которым могут работать все программы, а он уже дальше будет подключаться по TLS к dumbproxy на удалённом сервере.
