### ISSUE TITLE
CRITICAL TLS config construction failed: tls: failed to parse private key

### ISSUE THREAD

**Issue by Spp595** [Snawoot/dumbproxy#48]
Создаю самоподписаный сертификат командой: `openssl req -x509 -newkey rsa:2048 -keyout key.key -out cert.crt -days 3650`
Далее использую данную команду для запуска прокси: `./dumbproxy -bind-address :443 -auth 'static://?username=admin&password=123456' -cert cert.crt -key key.key`

Ошибка: `MAIN    : 2024/01/09 10:44:37 main.go:177: INFO     Starting proxy server...
MAIN    : 2024/01/09 10:44:37 main.go:208: CRITICAL TLS config construction failed: tls: failed to parse private key
root@static:~/proxy# `

Мне бы хотелось бы использовать https прокси без доменному имени

**Comment by Snawoot** [comment]
@Spp595 dumbproxy не принимает зашифрованные паролем приватные ключи. Нужно либо сгенерировать сертификат с ключом без пароля (добавить опцию `-nodes`), либо [расшифровать имеющийся ключ и убрать пароль](https://help.cloud66.com/docs/security/remove-passphrase).

> Мне бы хотелось бы использовать https прокси без доменному имени

Работать с таким прокси будет сложнее, придётся как-то обеспечить доверие такому самоподписанному серту. Либо настраивать клиентов чтобы принимали любой сертификат, но тогда это по большей части лишает затею смысла -- такая конфигурация небезопасна.

**Comment by Spp595** [comment]
ок, буду тогда freemyip использовать(((
