### ISSUE TITLE
Extra logging foe cert:// auth scheme

### ISSUE THREAD

**Issue by akliouev** [Snawoot/dumbproxy#7]
I'm struggling with the setup to allow certificate-based authentication for the proxy. I've set up my own CA and generated a bunch of keys for my clients but both windows and osx ones seems to fail to authenticate with the given client cert. The server side logging is set to verbosity 10 but nothing is being logged. Is there any way to make the logging more verbose for cert-based auth and also an idea -- any way to log the username/client certificate CN for proxied requests?

**Comment by Snawoot** [comment]
> Is there any way to make the logging more verbose for cert-based auth and also an idea -- any way to log the username/client certificate CN for proxied requests?

None at this moment, unless make changes to handle certificate verifications with custom verifier and log such events.

It's quite difficult to make browsers work right with proxies having mutual TLS authentication. Even if they will work, sometimes authentication getting lost and browser forgets auth, requesting once again to pick cert to authenticate itself to a server. It makes sense to use an adapter which handles client auth and also keeps pool of prepared connections: https://github.com/Snawoot/steady-tun This way it will be available for all platforms and compatible with all software which support any HTTP proxies.
